print (' ======= Exercício  09 ======= ')
print (' *** Tabuada ***')
n = int(input ('insira um número para ver sua tabuada: '))

print (' =================== ')
a=n*1; print ('{} x 1 = {}'.format (n,a))
b=n*2; print ('{} x 2 = {}'.format (n,b))
c=n*3; print ('{} x 3 = {}'.format (n,c))
d=n*4; print ('{} x 4 = {}'.format (n,d))
e=n*5; print ('{} x 5 = {}'. format (n,e))
f=n*6; print ('{} x 6 = {}'.format (n,f))
g=n*7; print ('{} x 7 = {}'.format (n,g))
h=n*8; print ('{} x 8 = {}'.format (n,h))
i=n*9; print ('{} x 9 = {}'.format (n,i))
j=n*10; print ('{} x 10= {}'.format (n,j))
print (' =================== ')